In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
from sklearn.neighbors import KNeighborsClassifier

In [6]:
cancer = pd.read_csv('./data_cancer/cancer2.csv')
cancer

       1   5   4   3  1.1   2  2.1  2.2  3.1  1.2  0
0      2   9   1   2    6   4   10    7    7    2  1
1      3  10   4   7    2   2    8    6    1    1  1
2      4   6  10  10   10   8   10    7   10    7  1
3      5   1   1   1    1   2    5    5    1    1  0
4      6   7   6  10    5   3   10    9   10    2  1
5      7   8  10  10    8   5   10    7    8    1  1
6      8   8   4   4    1   2    9    3    3    1  1
7      9   5   8   8   10   5   10    8   10    3  1
8     10   4   1   1    1   2    1    3    6    1  0
9     11   3   1   1    1   2    1    3    1    1  0
10    12   1   2   2    1   2    1    1    1    1  0
11    13   3   1   1    1   2    1    2    1    1  0
12    14   5   3   2    8   5   10    8    1    2  1
13    15  10   4   4   10   2   10    5    3    3  1
14    16   5   7   7    1   5    8    3    4    1  0
15    17  10   5   8   10   3   10    5    1    3  1
16    18   5  10  10    6  10   10   10    6    5  1
17    19   8   8   9    4   5   10    7    8    1  1
18    20  10   4   4   10   6   10    5    5    1  1
19    21   7   9   4   10  10    3    5    3    3  1
20    22   3   3   5    2   3   10    7    1    1  1
21    23   3   3   5    2   3   10    7    1    1  1
22    24   1   1   1    1   2    1    2    1    1  0
23    25  10   8   8    2   3    4    8    7    8  1
24    26   1   1   1    1   3    1    1    1    1  0
25    27   1   1   3    1   2    1    1    1    1  0
26    28  10   5  10    3   5    8    7    8    3  1
27    29   4   1   1    2   2    1    1    1    1  0
28    30   4   1   1    1   3    1    1    1    1  0
29    31  10   9   7    3   4    2    7    7    1  1
..   ...  ..  ..  ..  ...  ..  ...  ...  ...  ... ..
622  624   1   1   1    1   2    1    2    1    1  0
623  625   4   1   1    1   2    1    3    1    1  0
624  626   8   4   4    1   6   10    2    5    2  1
625  627  10  10   8   10   6    5   10    3    1  1
626  628   8  10   4    4   8   10    8    2    1  1
627  629   1   1   1    1   1    1    2    1    1  0
628  630   1   1   3    1   2    1    2    1    1  0
629  631   3   1   1    3   2    1    2    1    1  0
630  632   1   1   1    1   2    1    1    1    1  0
631  633   5   2   2    2   2    1    1    1    2  0
632  634   3   1   1    1   2    1    3    1    1  0
633  635   5   7   4    1   6    1    7   10    3  1
634  636   5  10  10    8   5    5    7   10    1  1
635  637   4   1   1    1   2    1    2    1    1  0
636  638   5   4   6    8   4    1    8   10    1  1
637  639   3  10   7    8   5    8    7    4    1  1
638  640   3   2   1    2   2    1    3    1    1  0
639  641   2   1   1    1   2    1    3    1    1  0
640  642   5   3   2    1   3    1    1    1    1  0
641  643   1   1   1    1   2    1    2    1    1  0
642  644   4   1   4    1   2    1    1    1    1  0
643  645   1   1   2    1   2    1    2    1    1  0
644  646   5   1   1    1   2    1    1    1    1  0
645  647   1   1   1    1   2    1    1    1    1  0
646  648   2   1   1    1   2    1    1    1    1  0
647  649  10  10  10   10   5   10   10   10    7  1
648  650   5  10  10   10   4   10    5    6    3  1
649  651   5   1   1    1   2    1    3    2    1  0
650  652   4   1   1    1   1    1    2    1    1  0
651  653   1   1   3    1   2    1    2    1    1  0

[652 rows x 11 columns]

In [5]:
# cancer = pd.read_csv('./data_cancer/cancer.csv')
# cancer

     1000025   5   1  1.1  1.2  2 1.3   3  1.4  1.5  2.1
0    1002945   5   4    4    5  7  10   3    2    1    2
1    1015425   3   1    1    1  2   2   3    1    1    2
2    1016277   6   8    8    1  3   4   3    7    1    2
3    1017023   4   1    1    3  2   1   3    1    1    2
4    1017122   8  10   10    8  7  10   9    7    1    4
5    1018099   1   1    1    1  2  10   3    1    1    2
6    1018561   2   1    2    1  2   1   3    1    1    2
7    1033078   2   1    1    1  2   1   1    1    5    2
8    1033078   4   2    1    1  2   1   2    1    1    2
9    1035283   1   1    1    1  1   1   3    1    1    2
10   1036172   2   1    1    1  2   1   2    1    1    2
11   1041801   5   3    3    3  2   3   4    4    1    4
12   1043999   1   1    1    1  2   3   3    1    1    2
13   1044572   8   7    5   10  7   9   5    5    4    4
14   1047630   7   4    6    4  6   1   4    3    1    4
15   1048672   4   1    1    1  2   1   2    1    1    2
16   1049815   4   1    1    1  2   1   3    1    1    2
17   1050670  10   7    7    6  4  10   4    1    2    4
18   1050718   6   1    1    1  2   1   3    1    1    2
19   1054590   7   3    2   10  5  10   5    4    4    4
20   1054593  10   5    5    3  6   7   7   10    1    4
21   1056784   3   1    1    1  2   1   2    1    1    2
22   1057013   8   4    5    1  2   ?   7    3    1    4
23   1059552   1   1    1    1  2   1   3    1    1    2
24   1065726   5   2    3    4  2   7   3    6    1    4
25   1066373   3   2    1    1  1   1   2    1    1    2
26   1066979   5   1    1    1  2   1   2    1    1    2
27   1067444   2   1    1    1  2   1   2    1    1    2
28   1070935   1   1    3    1  2   1   1    1    1    2
29   1070935   3   1    1    1  1   1   2    1    1    2
..       ...  ..  ..  ...  ... ..  ..  ..  ...  ...  ...
668  1350423   5  10   10    8  5   5   7   10    1    4
669  1352848   3  10    7    8  5   8   7    4    1    4
670  1353092   3   2    1    2  2   1   3    1    1    2
671  1354840   2   1    1    1  2   1   3    1    1    2
672  1354840   5   3    2    1  3   1   1    1    1    2
673  1355260   1   1    1    1  2   1   2    1    1    2
674  1365075   4   1    4    1  2   1   1    1    1    2
675  1365328   1   1    2    1  2   1   2    1    1    2
676  1368267   5   1    1    1  2   1   1    1    1    2
677  1368273   1   1    1    1  2   1   1    1    1    2
678  1368882   2   1    1    1  2   1   1    1    1    2
679  1369821  10  10   10   10  5  10  10   10    7    4
680  1371026   5  10   10   10  4  10   5    6    3    4
681  1371920   5   1    1    1  2   1   3    2    1    2
682   466906   1   1    1    1  2   1   1    1    1    2
683   466906   1   1    1    1  2   1   1    1    1    2
684   534555   1   1    1    1  2   1   1    1    1    2
685   536708   1   1    1    1  2   1   1    1    1    2
686   566346   3   1    1    1  2   1   2    3    1    2
687   603148   4   1    1    1  2   1   1    1    1    2
688   654546   1   1    1    1  2   1   1    1    8    2
689   654546   1   1    1    3  2   1   1    1    1    2
690   695091   5  10   10    5  4   5   4    4    1    4
691   714039   3   1    1    1  2   1   1    1    1    2
692   763235   3   1    1    1  2   1   2    1    2    2
693   776715   3   1    1    1  3   2   1    1    1    2
694   841769   2   1    1    1  2   1   1    1    1    2
695   888820   5  10   10    3  7   3   8   10    2    4
696   897471   4   8    6    4  3   4  10    6    1    4
697   897471   4   8    8    5  4   5  10    4    1    4

[698 rows x 11 columns]

In [7]:
cancer.head() #1好   0出

   1   5   4   3  1.1  2  2.1  2.2  3.1  1.2  0
0  2   9   1   2    6  4   10    7    7    2  1
1  3  10   4   7    2  2    8    6    1    1  1
2  4   6  10  10   10  8   10    7   10    7  1
3  5   1   1   1    1  2    5    5    1    1  0
4  6   7   6  10    5  3   10    9   10    2  1

In [8]:
cancer.shape

(652, 11)

In [27]:
X = cancer.iloc[:,2:]
y=cancer.iloc[:,10:11]
y.head()

   0
0  1
1  1
2  1
3  0
4  1

In [28]:
X

      4   3  1.1   2  2.1  2.2  3.1  1.2  0
0     1   2    6   4   10    7    7    2  1
1     4   7    2   2    8    6    1    1  1
2    10  10   10   8   10    7   10    7  1
3     1   1    1   2    5    5    1    1  0
4     6  10    5   3   10    9   10    2  1
5    10  10    8   5   10    7    8    1  1
6     4   4    1   2    9    3    3    1  1
7     8   8   10   5   10    8   10    3  1
8     1   1    1   2    1    3    6    1  0
9     1   1    1   2    1    3    1    1  0
10    2   2    1   2    1    1    1    1  0
11    1   1    1   2    1    2    1    1  0
12    3   2    8   5   10    8    1    2  1
13    4   4   10   2   10    5    3    3  1
14    7   7    1   5    8    3    4    1  0
15    5   8   10   3   10    5    1    3  1
16   10  10    6  10   10   10    6    5  1
17    8   9    4   5   10    7    8    1  1
18    4   4   10   6   10    5    5    1  1
19    9   4   10  10    3    5    3    3  1
20    3   5    2   3   10    7    1    1  1
21    3   5    2   3   10    7    1    1  1
22    1   1    1   2    1    2    1    1  0
23    8   8    2   3    4    8    7    8  1
24    1   1    1   3    1    1    1    1  0
25    1   3    1   2    1    1    1    1  0
26    5  10    3   5    8    7    8    3  1
27    1   1    2   2    1    1    1    1  0
28    1   1    1   3    1    1    1    1  0
29    9   7    3   4    2    7    7    1  1
..   ..  ..  ...  ..  ...  ...  ...  ... ..
622   1   1    1   2    1    2    1    1  0
623   1   1    1   2    1    3    1    1  0
624   4   4    1   6   10    2    5    2  1
625  10   8   10   6    5   10    3    1  1
626  10   4    4   8   10    8    2    1  1
627   1   1    1   1    1    2    1    1  0
628   1   3    1   2    1    2    1    1  0
629   1   1    3   2    1    2    1    1  0
630   1   1    1   2    1    1    1    1  0
631   2   2    2   2    1    1    1    2  0
632   1   1    1   2    1    3    1    1  0
633   7   4    1   6    1    7   10    3  1
634  10  10    8   5    5    7   10    1  1
635   1   1    1   2    1    2    1    1  0
636   4   6    8   4    1    8   10    1  1
637  10   7    8   5    8    7    4    1  1
638   2   1    2   2    1    3    1    1  0
639   1   1    1   2    1    3    1    1  0
640   3   2    1   3    1    1    1    1  0
641   1   1    1   2    1    2    1    1  0
642   1   4    1   2    1    1    1    1  0
643   1   2    1   2    1    2    1    1  0
644   1   1    1   2    1    1    1    1  0
645   1   1    1   2    1    1    1    1  0
646   1   1    1   2    1    1    1    1  0
647  10  10   10   5   10   10   10    7  1
648  10  10   10   4   10    5    6    3  1
649   1   1    1   2    1    3    2    1  0
650   1   1    1   1    1    2    1    1  0
651   1   3    1   2    1    2    1    1  0

[652 rows x 9 columns]

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score #测试评估包

In [30]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [32]:
X_train.shape

(521, 9)

In [33]:
X_test.shape

(131, 9)

In [41]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)

y_ = knn.predict(X_test)
display(y_,y_test.values)

C:\Users\陈文亮\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
      dtype=int64)

array([[1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0]], dtype=int64)

In [42]:
accuracy_score(y_test,y_) #准确率0.97 这是我的想法

0.9770992366412213

In [43]:
knn.score(X_test,y_test) #0.9770992366412213

0.9770992366412213

In [56]:
#知道多少个没病的 成有病的,有病的成没病
pd.crosstab(index=y_test.values.T,columns= y_) #求表数据的差异

Exception: Data must be 1-dimensional

In [58]:
y_.shape
y_

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
      dtype=int64)

In [46]:
y_test.shape

(131, 1)

In [54]:
y_test.values.T

array([[1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
        1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
        0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
        0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0]],
      dtype=int64)

In [59]:
from sklearn.metrics import confusion_matrix #sklearn内置交叉表

In [60]:
confusion_matrix(y_test,y_)

array([[79,  1],
       [ 2, 49]], dtype=int64)

In [61]:
from sklearn.metrics import classification_report #评估报告

In [63]:
report = classification_report(y_test,y_)
print(report) #有//换行,需要print才看的清楚
#precision    精确率

              precision    recall  f1-score   support

           0       0.98      0.99      0.98        80
           1       0.98      0.96      0.97        51

   micro avg       0.98      0.98      0.98       131
   macro avg       0.98      0.97      0.98       131
weighted avg       0.98      0.98      0.98       131

In [66]:
49/51

0.9607843137254902

In [67]:
79/80

0.9875

In [68]:
from sklearn.preprocessing import StandardScaler #大写的是一个类

In [76]:
#归一化 ,标准化
s = StandardScaler()
X2 = s.fit_transform(X) #->np数据类型

D:\Coding\Anaconda3-5.3.1-Windows-x86_64\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
D:\Coding\Anaconda3-5.3.1-Windows-x86_64\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

In [77]:
X2[:5]

array([[-0.69523233, -0.40635551,  1.11531116,  0.36073928,  1.78331965,
         1.4624287 ,  1.34182803,  0.22440263,  1.38228589],
       [ 0.28521067,  1.27262924, -0.28311745, -0.54737659,  1.23174261,
         1.05529654, -0.60810929, -0.34489899,  1.38228589],
       [ 2.24609667,  2.28002009,  2.51373977,  2.17697102,  1.78331965,
         1.4624287 ,  2.31679669,  3.07091075,  1.38228589],
       [-0.69523233, -0.74215246, -0.6327246 , -0.54737659,  0.40437704,
         0.64816438, -0.60810929, -0.34489899, -0.72343935],
       [ 0.93883933,  2.28002009,  0.76570401, -0.09331866,  1.78331965,
         2.27669301,  2.31679669,  0.22440263,  1.38228589]])

In [78]:
X_train,X_test,y_train,y_test = train_test_split(X2,y,test_size=0.2)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)

y_ = knn.predict(X_test)
accuracy_score(y_test,y_)

C:\Users\陈文亮\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

1.0